# 测试环境配置
# ==========================================

# 基础交易配置
trading:
  ticker: "AAPL"
  exchange: "ARCA"
  currency: "USD"
  initial_capital: 50000.0  # 测试环境中等资金
  benchmark: "SPY"

# 数据配置
data:
  timeframe: "30min"
  history_years: 3
  train_days: 800
  volatility_window: 45
  trade_frequency_minutes: 60

# 模型配置
model:
  update_interval_days: 2
  min_samples: 35
  rolling_window: 70
  feature_selection_method: "mutual_info"
  enable_model_monitor: true
  walkforward_test_window: 90
  walkforward_step: 60

# 风险管理
risk_management:
  risk_per_trade: 0.015
  max_trade_percentage: 0.08
  stop_loss_multiplier: 1.6
  take_profit_multiplier: 2.2
  max_drawdown: 0.08
  daily_loss_limit: -0.025

# 交易成本
costs:
  transaction_cost: 0.0008
  slippage: 0.0015

# 自适应阈值配置
adaptive_threshold:
  initial_threshold: 0.78
  transition_covariance: 0.015
  observation_covariance: 1.2
  confirm_signal_k: 2
  atr_threshold: 0.018

# 系统控制
system:
  live_trading: false
  max_retries: 4
  enable_crash_recovery: true
  log_level: "INFO"
  use_best_params: true    # 测试环境使用最佳参数

# API配置
api:
  twelve_data_api_key: null



