# 生产环境配置
# ==========================================

# 基础交易配置
trading:
  ticker: "AAPL"
  exchange: "ARCA"
  currency: "USD"
  initial_capital: 100000.0  # 生产环境完整资金
  benchmark: "SPY"

# 数据配置
data:
  timeframe: "30min"
  history_years: 5    # 完整历史数据
  train_days: 1260    # 充足的训练数据
  volatility_window: 60
  trade_frequency_minutes: 60

# 模型配置
model:
  update_interval_days: 3     # 稳定的更新频率
  min_samples: 50            # 充足的样本要求
  rolling_window: 98         # 标准滚动窗口
  feature_selection_method: "shap_dynamic"  # 最佳特征选择
  enable_model_monitor: true
  walkforward_test_window: 120
  walkforward_step: 120

# 风险管理（生产环境平衡风险收益）
risk_management:
  risk_per_trade: 0.02
  max_trade_percentage: 0.1
  stop_loss_multiplier: 1.8
  take_profit_multiplier: 2.5
  max_drawdown: 0.1
  daily_loss_limit: -0.03

# 交易成本（真实市场成本）
costs:
  transaction_cost: 0.0005
  slippage: 0.001

# 自适应阈值配置
adaptive_threshold:
  initial_threshold: 0.75
  transition_covariance: 0.01
  observation_covariance: 1.0
  confirm_signal_k: 3
  atr_threshold: 0.015

# 系统控制
system:
  live_trading: true      # 生产环境启用实盘交易
  max_retries: 5
  enable_crash_recovery: true
  log_level: "WARNING"    # 生产环境减少日志
  use_best_params: true   # 使用优化后的最佳参数

# API配置
api:
  twelve_data_api_key: null  # 必须从环境变量读取

