# 开发环境配置
# ==========================================

# 基础交易配置
trading:
  ticker: "AAPL"
  exchange: "ARCA"
  currency: "USD"
  initial_capital: 10000.0  # 开发环境使用较小资金
  benchmark: "SPY"

# 数据配置
data:
  timeframe: "30min"
  history_years: 2  # 开发环境使用较少历史数据
  train_days: 500   # 减少训练数据以加快开发
  volatility_window: 30
  trade_frequency_minutes: 60

# 模型配置
model:
  update_interval_days: 1  # 开发环境更频繁更新
  min_samples: 20         # 降低最小样本要求
  rolling_window: 50      # 减少滚动窗口
  feature_selection_method: "correlation"  # 使用简单方法
  enable_model_monitor: true
  walkforward_test_window: 60
  walkforward_step: 30

# 风险管理（开发环境更保守）
risk_management:
  risk_per_trade: 0.01     # 更低风险
  max_trade_percentage: 0.05
  stop_loss_multiplier: 1.5
  take_profit_multiplier: 2.0
  max_drawdown: 0.05
  daily_loss_limit: -0.02

# 交易成本
costs:
  transaction_cost: 0.001  # 稍高的成本模拟
  slippage: 0.002

# 自适应阈值配置
adaptive_threshold:
  initial_threshold: 0.8
  transition_covariance: 0.02
  observation_covariance: 1.5
  confirm_signal_k: 2
  atr_threshold: 0.02

# 系统控制
system:
  live_trading: false      # 开发环境禁用实盘交易
  max_retries: 3
  enable_crash_recovery: true
  log_level: "DEBUG"       # 详细日志
  use_best_params: false   # 不使用最佳参数

# API配置
api:
  twelve_data_api_key: null  # 从环境变量读取

